name: Java Workflow
on:
  workflow_dispatch:
  push: 
    branches: 
      - main
env:
    Grußformel: grußformel
    
jobs:
  console:
    runs-on:
      ubuntu-latest
    env:
      Begrueßter: Irgendjemand
    steps:
        - name: ausgebe
          env: 
            Passwortnutzen: keinen
        - name: Checkout-repository
          uses: actions/checkout@v4
        - name: Ausgabe 
          run: echo $Grußformel $Begrueßter , das Passwort für $Passwortnutzen ist $Passwort
      
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11,17,21]
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '${{matrix.java-version}}'
      - name: Build and Test with Maven
        run: mvn -B clean verify
      - name: Archive Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4
      - name: checkstyle
        run: mvn checkstyle:checkstyle
      - name: Archive Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-result
          path: target/checkstyle-result.xml
        
