name: Java Workflow
on:
  workflow_dispatch:
  push: 
    branches: 
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '21'
      - name: Build and Test with Maven
        run: mvn -B clean verify
      - name: Archive Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4
      - name: checkstyle
        run: mvn checkstyle:check
      - name: Archive Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: check-style-result
          path: target/checkstyle-result.xml
        
